apiVersion: v1
kind: Secret
metadata:
  name: {{ include "parasol-web.name" . }}-registry-creds-app
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: | 
    {
      "username": "{{ .Values.registry.username }}",
      "password": "{{ .Values.registry.password }}",
      "auths": {
        "{{ .Values.image.host }}": {
          "auth": "{{ include "quay.auth" . }}"
        }
      }
    }
